spring:
  application:
    name: api-gateway
  liquibase:
    enabled: false

server:
  port: 7777

application:
  api-routes:
    - id: "service-authorization"
      from: "api/v1/auth"
      to: "lb://SERVICE-AUTHORIZATION"
    - id: "service-user"
      from: "api/v1/user"
      to: "lb://SERVICE-USER"
    - id: "service-order"
      from: "api/v1/order"
      to: "lb://SERVICE-ORDER"
    - id: "service-resume"
      from: "api/v1/resume"
      to: "lb://SERVICE-RESUME"
    - id: "service-notification"
      from: "api/v1/notification"
      to: "lb://SERVICE-NOTIFICATION"


eureka:
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:9999/eureka/}
  instance:
    lease-renewal-interval-in-seconds: 30
    metadataMap:
      zone: zone1

management:
  tracing:
    sampling:
      probability: 1.0
  endpoint:
    prometheus:
      enabled: true
    metrics:
      enabled: true
    health:
      enabled: true
      probes:
        enabled: true
    refresh:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - prometheus
          - health
          - metrics
          - refresh
    enabled-by-default: false