server:
  port: 8083

spring:
  application:
    name: service-resume
  datasource:
    url: jdbc:h2:mem:resumeDb
  jpa:
    generate-ddl: false
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
  h2:
    console.enabled: true
  liquibase:
    enabled: true
    change-log: liquibase/changelog.master.yml

eureka:
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:9999/eureka/}
  instance:
    lease-renewal-interval-in-seconds: 30
    metadataMap:
      zone: zone1