spring:
  application:
    name: service-user
#    instance_id: i0
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/mainDb
#    username: postgres
#    password: postgres
  datasource:
    url: jdbc:h2:mem:userDb
  jpa:
    generate-ddl: false
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
    change-log: liquibase/changelog.master.yml
  h2:
    console.enabled: true

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379

server:
  port: 8080

eureka:
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:9999/eureka/}
  instance:
    lease-renewal-interval-in-seconds: 30
    metadataMap:
      zone: zone1